homepage:
    path:     /
    defaults: { _controller: FrontEndFrontOfficeBundle:Index:index }

login_check:
    path:     /login_check
    defaults: { _controller: FrontEndFrontOfficeBundle:Index:loginCheck }
    
logout:
    path:     /logout
    defaults: { _controller: FrontEndFrontOfficeBundle:Index:logout }
    
projets-index:
    path:     /projets
    defaults: { _controller: FrontEndFrontOfficeBundle:Projets:projets }
    
projets-details:
    path:     /projets/infos/{id}/{name}
    defaults: { _controller: FrontEndFrontOfficeBundle:Projets:details }
    
projets-edition:
    path:     /projets/infos/{id}/{name}/edition
    defaults: { _controller: FrontEndFrontOfficeBundle:Projets:edit }

projets-creation:
    path:     /projets/creation
    defaults: { _controller: FrontEndFrontOfficeBundle:Projets:create }

tasks-creation:
    path:     /projets/{project_id}/{project_name}/tasks/creation
    defaults: { _controller: FrontEndFrontOfficeBundle:Tasks:create }
    
tasks-edition:
    path:     /projets/{project_id}/{project_name}/tasks/{id}/edition
    defaults: { _controller: FrontEndFrontOfficeBundle:Tasks:edit }
    
tasks-delete:
    path:     /projets/{project_id}/{project_name}/tasks/{id}/delete
    defaults: { _controller: FrontEndFrontOfficeBundle:Tasks:delete }