<?php

namespace FrontEnd\FrontOfficeBundle\Entity;

/**
 * Task_StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Task_StateRepository extends \Doctrine\ORM\EntityRepository
{
}
