<?php

namespace FrontEnd\FrontOfficeBundle\Entity;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastTaskToDo($limit)
    {
        $query = $this->createQueryBuilder('t')
            ->addSelect('t.name')
            ->addSelect('pr.name as project')
            ->addSelect('p.id as prio_id')
            ->addSelect('p.name as prio_name')
            ->addSelect('s.id as state_id')
            ->addSelect('s.name as state_name')
            ->leftjoin('t.project', 'pr')
            ->leftjoin('t.priority', 'p')
            ->leftjoin('t.state', 's')
            ->where('s.id != '.Task_State::DONE)
            ->andWhere('s.id != '.Task_State::CANCELLED)
            ->orderby('t.priority', 'ASC')
            ->addOrderby('t.addedAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery();
            
        return $query->getResult();
    }
    
    public function findByProject($id)
    {
        $query = $this->createQueryBuilder('t')
            ->addSelect('t.id')
            ->addSelect('t.name')
            ->addSelect('t.comment')
            ->addSelect('t.addedAt')
            ->addSelect('p.id as prio_id')
            ->addSelect('p.name as prio_name')
            ->addSelect('s.id as state_id')
            ->addSelect('s.name as state_name')
            ->leftjoin('t.project', 'pr')
            ->leftjoin('t.priority', 'p')
            ->leftjoin('t.state', 's')
            ->where('t.project = :project')
            ->setParameter('project', $id)
            ->orderBy('t.priority', 'ASC')
            ->addOrderBy('t.state', 'ASC')
            ->getQuery();
            
        return $query->getResult();
    }
    
    public function getAllTasks()
    {
         $query = $this->createQueryBuilder('t')
            ->addSelect('t.id')
            ->addSelect('t.name')
            ->addSelect('t.comment')
            ->addSelect('t.addedAt')
            ->addSelect('p.id as prio_id')
            ->addSelect('p.name as prio_name')
            ->addSelect('s.id as state_id')
            ->addSelect('s.name as state_name')
            ->addSelect('pr.id as proj_id')
            ->leftjoin('t.project', 'pr')
            ->leftjoin('t.priority', 'p')
            ->leftjoin('t.state', 's')
            ->orderBy('pr.id', 'ASC')
            ->addOrderBy('t.state', 'ASC')
            ->addOrderBy('t.priority', 'ASC')
            ->getQuery();
            
        return $query->getResult();
    }
}
