<?php

namespace FrontEnd\FrontOfficeBundle\Entity;

/**
 * Task_PriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Task_PriorityRepository extends \Doctrine\ORM\EntityRepository
{
}
